# Generated by Django 4.2.6 on 2023-10-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comapany',
            old_name='active',
            new_name='added_date',
        ),
        migrations.AddField(
            model_name='comapany',
            name='activr',
            field=models.BooleanField(default=True),
        ),
    ]
