# Generated by Django 4.2.6 on 2023-10-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_active_comapany_added_date_comapany_activr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapany',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='activr',
            new_name='active',
        ),
    ]
