# Generated by Django 4.2.6 on 2023-10-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_comapany_company_rename_activr_company_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
    ]
