# Generated by Django 4.2.6 on 2023-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_comapny_id_company_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Manager', 'manager'), ('Software Developer', 'Software Developer'), ('Project Leader', 'Project Leader')], default=False, max_length=50),
        ),
    ]
